export default [

    {
        id:'1',
        name:"Ayush",
        number:"6546587896",
        image:require("./assets/Images/profileavatar.png")
    },
    {
        id:'2',
        name:"Vivek",
        number:"65468796846",
        image:require("./assets/Images/profileavatar.png")
    },{
        id:'3',
        name:"Aryaman",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'4',
        name:"Ankit",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'5',
        name:"Arjun",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'6',
        name:"Amit",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'7',
        name:"Ankur",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'8',
        name:"Nilesh",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'9',
        name:"Adarsh",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'10',
        name:"Jitesh",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'11',
        name:"Pranshu",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'12',
        name:"Rakesh",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'13',
        name:"Arpit",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'14',
        name:"Yugank",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'15',
        name:"Anand",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }
    ,{
        id:'16',
        name:"Nitesh",
        number:"5456546545",
        image:require("./assets/Images/profileavatar.png")
    }

    
    ]